export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Landing } from './Landing/Landing'
export { default as FormRegisto } from './FormRegisto/FormRegisto'
export { default as DashBoardNav } from './DashBoardNav/DashBoardNav'
export { default as Pacientes } from './Pacientes/Pacientes'
export { default as Categorias } from './Categorias/Categorias'